name: Tests
on: [push, workflow_dispatch]
jobs:
  job:
    name: configure & build & test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: lukka/get-cmake@v.3.23.2

      - name: Run CMake to build
        uses: lukka/run-cmake@v10
        with:
          configurePreset: default
          buildPreset: default
          testPreset: default
