name: Evergreen master
on:
  push:
    branches:
      - master

jobs:
  job:
    name: configure, build & test
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download and cache CMake
        uses: lukka/get-cmake@v.3.23.2

      - name: Build all
        run: cmake --preset default && cmake --build --preset default

      - name: Test all
        run: ctest --preset default
