name: Submission
on:
  workflow_call:
    inputs:
      submission_ref:
        required: true
        type: string

jobs:
  build_job:
    name: configure & build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.submission_ref }}

      - uses: lukka/get-cmake@v.3.23.2

      - name: Run CMake to build
        uses: lukka/run-cmake@v10
        with:
          configurePreset: default
          buildPreset: default

      - name: Tar artifacts
        run: tar -cvf test_oracle.tar builds/default/oracle/test_oracle

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test_oracle
          path: test_oracle.tar
          retention-days: 1

  test_job:
    name: test
    runs-on: ubuntu-latest
    needs: build_job

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: test_oracle

      - name: Untar artifacts
        run: tar -xvf test_oracle.tar

      - shell: bash
        run: |
          ./builds/default/oracle/test_oracle
