name: Submission
on:
  workflow_call:
    inputs:
      submission_ref:
        required: true
        type: string
      task_name:
        required: true
        type: string
    secrets:
      PRIVATE_TESTS_TOKEN:
        required: true
env:
  TEST_EXECUTABLE_PATH: builds/default/${{ inputs.task_name }}/test_${{ inputs.task_name }}

jobs:
  build_job:
    name: configure & build
    runs-on: ubuntu-20.04

    env:
      TASK_NAME: ${{ inputs.task_name }}
      TEST_TARGET: test_${{ inputs.task_name }}

    steps:
      - name: Download and cache CMake
        uses: lukka/get-cmake@v.3.23.2

      - name: Checkout canonical repository
        uses: actions/checkout@v3
        with:
          repository: group2022-famcs/playground-for-private-tests
          submodules: true
          ssh-key: ${{ secrets.PRIVATE_TESTS_TOKEN }}
          ref: master
          persist-credentials: false

      - name: Checkout submission
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.submission_ref }}
          persist-credentials: false
          path: submission

      - name: "Replace '${{ env.TASK_NAME }}' sources with submission"
        run: |
          bash -c 'shopt -s extglob
          mv \
          "submission/${{ env.TASK_NAME }}"/!(*_test|_utility).cpp \
          "submission/${{ env.TASK_NAME }}"/!(*_utility).h \
          "${{ env.TASK_NAME }}"'

      - name: "Replace '${{ env.TASK_NAME }}' tests with private tests"
        run: mv "private-tests-holder/${{ env.TASK_NAME }}"/*_test.cpp "${{ env.TASK_NAME }}"

      - name: Build '${{ env.TASK_NAME }}'
        run: cmake --preset default && cmake --build --preset default -t "${{ env.TEST_TARGET }}"

      - name: Tar artifacts
        run: tar -cvf build_artifacts.tar "${{ env.TEST_EXECUTABLE_PATH }}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build_artifacts
          path: build_artifacts.tar
          retention-days: 1

  test_job:
    name: test
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/group2022-famcs/isolated-bare-env
      credentials:
        username: group2022-famcs
        password: ${{ secrets.github_token }}

    needs: build_job

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: build_artifacts

      - name: Untar artifacts
        run: tar -xvf build_artifacts.tar

      - name: Test '${{ inputs.task_name }}'
        run: env -i "./${{ env.TEST_EXECUTABLE_PATH }}"
