name: Submission
on:
  workflow_call:
    inputs:
      submission_ref:
        required: true
        type: string
      task_name:
        required: true
        type: string
env:
  TEST_EXECUTABLE_PATH: builds/default/${{ inputs.task_name }}/test_${{ inputs.task_name }}

jobs:
  build_job:
    name: configure & build
    runs-on: ubuntu-20.04

    env:
      TASK_NAME: ${{ inputs.task_name }}
      TEST_TARGET: test_${{ inputs.task_name }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.submission_ref }}

      - name: Download and cache CMake
        uses: lukka/get-cmake@v.3.23.2

      - name: Build '${{ env.TASK_NAME }}'
        run: cmake --preset default && cmake --build --preset default -t "${{ env.TEST_TARGET }}"

      - name: Tar artifacts
        run: tar -cvf build_artifacts.tar "${{ env.TEST_EXECUTABLE_PATH }}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build_artifacts
          path: build_artifacts.tar
          retention-days: 1

  test_job:
    name: test
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/group2022-famcs/isolated-bare-env
      credentials:
        username: group2022-famcs
        password: ${{ secrets.github_token }}

    needs: build_job

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: build_artifacts

      - name: Untar artifacts
        run: tar -xvf build_artifacts.tar

      - name: Test '${{ inputs.task_name }}'
        run: env -i "./${{ env.TEST_EXECUTABLE_PATH }}"
