name: Submission

on:
  pull_request_target:

jobs:
  call_submission_workflow:
    name: Run
    uses: group2022-famcs/playground-for-private-tests/.github/workflows/submission.yaml@master
    with:
      submission_ref: ${{ github.event.pull_request.head.sha }}