name: Looking for roadmen, gangsters and proper naughty boys

on:
  pull_request_target:

jobs:
  ci_config_check:
    name: Compare submission workflow config with canonical one
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: pull_request

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: base

      - run: cmp pull_request/.github/workflows/submission.yaml base/.github/workflows/submission.yaml

      - uses: andymckay/labeler@1.0.4
        with:
          add-labels: "trusted"

  call_workflow_submission:
    uses: group2022-famcs/playground-for-private-tests/.github/workflows/submission.yaml@master
